# Site settings
title: 이든 개발일지
description: 이든 개발일지
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eden-kr.github.io/"

# User settings
username: Eden
user_title: Portfolio
email: yjk7768@gmail.com
user_name : Eden Kim
#twitter_username: null
#github_username: eden-kr
#gplus_username:  null
#facebook_username: kty5859
#instagram_username: y._.eah

exclude: ['package.json', 'src' , 'node_modules']
