# Site settings
title: 이든 개발일지
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eden-kr.github.io/"

# User settings
username: eden
user_description: Hi, my name is eden.
user_title: Software Engineer
email: yjk7768@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
