# Site settings
title: 이든 개발일지
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eden-kr.github.io/"

# User settings
username: Eden
user_title: Portfolio
email: yjk7768@gmail.com
user_image : ![noname](https://user-images.githubusercontent.com/64695947/93841346-420f8f80-fcce-11ea-9a6f-c5935cd61526.png)
user_name : Eden Kim
user_descrption : Software Engineering · Industrial Management/n Client Developer · Siheung, Gyeonggi-do · 25

twitter_username: null
github_username: eden-kr
gplus_username:  null
facebook_username: kty5859
instagram_username: y._.eah

exclude: ['package.json', 'src' , 'node_modules']
